### ISSUE TITLE
ログのフォーマットを決める

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#24]
関連: #7 
## 検討事項
- いつ、どこで、何が発生して記録されたかわかるようなログになるように、ログのフォーマットを決める
## 考えていること
- 必要そうな情報
  - 日時
  - ログレベル
  - ロガーの呼び出し元
  - スタックトレース
- 非同期処理のことも考える必要あり？

**Comment by dodoichi** [comment]
> 非同期処理のことも考える必要あり？
> スレッドは出力して欲しいな。

**Comment by ta-chibana** [comment]
> スレッドは出力して欲しいな。

ありがとうございます！
スレッドを出力するのは、ログのつながりを明確にするためですかね？

また、**ロガーの呼び出し元**については、**ファイル名**と**行数**で良いのかなーと思っているのですがいかがでしょうか？

**Comment by ta-chibana** [comment]
> ロガーの呼び出し元については、ファイル名と行数で良いのかなーと思っているのですが~~いかがでしょうか？~~

個人的にはロガーの呼び出し元を判別するために、ファイル名と行数があれば良いのかなと思いました！
よって、フォーマットは以下の形になります。

```
%d [%-5level] [%thread] %file:%3line - %msg%n
```

出力例

```
2016-05-11 01:53:50,524 [DEBUG] [main] Slf4jSample.java: 10 - debug log
2016-05-11 01:53:50,531 [INFO ] [main] Foo.java: 13 - test!!
2016-05-11 01:53:50,538 [ERROR] [main] Slf4jSample.java: 23 - error log!
java.lang.NullPointerException: null
    at com.logtest.slf4j.Slf4jSample.main(Slf4jSample.java:21)
```

**Comment by dodoichi** [comment]
fileよりclassの方が一般的かな。FQCNのパッケージ名短縮にしてください。

**Comment by ta-chibana** [comment]
> fileよりclassの方が一般的かな。FQCNのパッケージ名短縮にしてください。

ふむふむ。こんな感じでしょうか。

```
%d [%-5level] [%thread] %class{25}:%3line - %msg%n
```

出力例

```
2016-05-13 02:00:16,148 [DEBUG] [main] c.l.slf4j.Slf4jSample: 10 - debug log
2016-05-13 02:00:16,151 [INFO ] [main] com.logtest.slf4j.Foo: 13 - test!!
2016-05-13 02:00:16,158 [ERROR] [main] c.l.slf4j.Slf4jSample: 23 - error log!
java.lang.NullPointerException: null
    at com.logtest.slf4j.Slf4jSample.main(Slf4jSample.java:21)
```

**Comment by dodoichi** [comment]
[![LGTM](http://lgtm.in/p/wCNsfS2qq)](http://lgtm.in/i/wCNsfS2qq)

**Comment by dodoichi** [comment]
[![LGTM](http://lgtm.in/p/yVQfaOteq)](http://lgtm.in/i/yVQfaOteq)

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/MQQ8p044q)](http://lgtm.in/i/MQQ8p044q)
